import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {fileURLToPath} from 'node:url';
import nunjucks from 'nunjucks';
import {readGitBlobBuffer} from './git-binary-reader.mjs';
import {galleryContract44r2 as contract,galleryContract46 as currentContract,galleryStatic44r2,galleryStatic46,assertGalleryDelta44r2,assertGallerySource44r2,assertGalleryAsset44r2,assertGallerySources44r2,assertGalleryHtml44r2,isDeferredGallery44r2,beforeGalleries44r2} from './project-galleries-44r2.mjs';
import {dialogFixture46} from './dialog-ui-46-fixture.mjs';
const root=fileURLToPath(new URL('../',import.meta.url));
const read=f=>fs.readFileSync(new URL('../'+f,import.meta.url),'utf8');
const html=()=>nunjucks.renderString(read('src/_includes/partials/project-proof-galleries.njk'),{projectProofs:currentContract.projects})+'<p>Progetti realizzati per configurare prodotti e supportare il lavoro commerciale.</p>';

test('44R2 history retained;46 has three authentic galleries,20 captures,60 exact derivatives',()=>assert.deepEqual(assertGallerySources44r2(root),{galleries:3,captures:20,derivatives:60,retainedHistoricalDerivatives:24,sourceDelta:'EXACT',coreContracts:'UNCHANGED'}));
test('44R2 exact inverse retains all homepage and configuration baseline bytes',()=>{for(const f of Object.keys(contract.edits)){const old=readGitBlobBuffer(contract.base,f,root).buffer.toString('utf8');assertGalleryDelta44r2(f,read(f),old);assert.equal(beforeGalleries44r2(f,read(f)),old.replace(/\r\n/g,'\n'));assert.throws(()=>assertGalleryDelta44r2(f,read(f)+'\nUnexpected delta',old));}});
test('44R2 refuses unrelated homepage wording and client-runtime publication',()=>{const f='src/index.njk',old=readGitBlobBuffer(contract.base,f,root).buffer.toString('utf8');assert.throws(()=>assertGalleryDelta44r2(f,read(f).replace('Trasformiamo prodotti','Inventiamo risultati'),old));const c='eleventy.config.js';assert.throws(()=>assertGalleryDelta44r2(c,read(c).replace('  "404.html",','  "client-app.js",\n  "404.html",'),readGitBlobBuffer(contract.base,c,root).buffer.toString('utf8')));});
test('44R2 rejects modified capture bytes, wrong dimensions and truncated metadata',()=>{const r=contract.images[0],b=fs.readFileSync(new URL('../'+r.file,import.meta.url));assertGalleryAsset44r2(b,r);const altered=Buffer.from(b);altered[altered.length-1]^=1;assert.throws(()=>assertGalleryAsset44r2(altered,r));assert.throws(()=>assertGalleryAsset44r2(b,{...r,width:r.width+1}));assert.throws(()=>assertGalleryAsset44r2(b.subarray(0,-1),r));});
test('44R2/46 refuses fabricated claims, removed image masking and changed project order',()=>{const f='src/_data/projectProofs.json',s=read(f);for(const changed of [s.replace('BiliardItaly','Invented Client'),s.replace('Dati riservati oscurati.','Risultati garantiti.'),s.replace('"id": "linea-oro"','"id": "pilan"')]){assert.notEqual(changed,s);assert.throws(()=>assertGallerySource44r2(f,changed));}});
test('44R2 refuses image shrinking, cropping, unreadable cover titles and changed UI tokens',()=>{const f='css/project-proof-galleries.css',s=read(f);for(const changed of [s.replace('width: 100%','width: 80%'),s.replace('object-fit: contain','object-fit: cover'),s.replace('.project-proof-rail .visual-card__copy h3 { color: var(--sx-text); }',''),s+'\nbody {background:red}'])assert.throws(()=>assertGallerySource44r2(f,changed));});
test('44R2/46 refuses missing modal safeguards, restoration or unsolicited autoplay',()=>{const f='js/project-proof-galleries.js',s=read(f);for(const changed of [s.replace('dialog.showModal()','dialog.show()'),s.replace('trigger.focus({ preventScroll: true });',''),s.replace('if (anotherSurfaceOpen(dialog)) return false;','if (false) return false;'),s+'\nsetInterval(()=>{},1000)']){assert.notEqual(changed,s);assert.throws(()=>assertGallerySource44r2(f,changed));}});
test('44R2 explicit Tab loop wraps both ends and preserves native middle navigation',()=>{
 const fixture=dialogFixture46(),document=fixture.document;
 const controls=[fixture.close,fixture.previous,fixture.next,fixture.large,fixture.galleryCta];
 fixture.click(fixture.galleryTrigger);
 for(const [from,shiftKey,to,prevented] of [[4,false,0,true],[0,true,4,true],[1,false,1,false],[2,true,2,false],[3,false,3,false]]){
  document.activeElement=controls[from];const event=fixture.gallery.emit('keydown',{key:'Tab',shiftKey});
  assert.equal(document.activeElement,controls[to]);assert.equal(event.prevented,prevented);
 }
 assert.throws(()=>assertGallerySource44r2('js/project-proof-galleries.js',read('js/project-proof-galleries.js').replace('(event.shiftKey ? last : first).focus({ preventScroll: true });','')));
});
test('44R2/46 rendered contract preserves native dialogs, fallback links and lazy large images',()=>assert.deepEqual(assertGalleryHtml44r2(html()),{galleries:3,views:20,progressiveFallback:true,largeImagesOnDemand:true}));
test('44R2/46 rendered negative cases reject eager images, bad srcset, missing close and fake reviews',()=>{const h=html();for(const changed of [h.replace('<img data-gallery-src=','<img src="/eager.webp" data-gallery-src='),h.replace('1440.webp 1440w','1440.webp 1300w'),h.replaceAll('data-gallery-close','removed-close'),h+'<script type="application/ld+json">{"@type":"Review"}</script>',h.replaceAll('href="/contattaci#contatti"','href="/new-form"')]){assert.notEqual(changed,h);assert.throws(()=>assertGalleryHtml44r2(changed));}});
test('44R2 deferred-image budget exception cannot whitelist arbitrary resources',()=>{const file=contract.images[0].file;assert.equal(isDeferredGallery44r2('<img loading="lazy">',file),true);assert.equal(isDeferredGallery44r2('<img>',file),false);assert.equal(isDeferredGallery44r2('<script loading="lazy">',file),false);assert.equal(isDeferredGallery44r2('<img loading="lazy">','client/database.json'),false);assert.equal(galleryStatic44r2.length,26);});
test('46 lossless derivatives retain exact pixels/dimensions and a bounded lazy-image exception',()=>{const r=currentContract.images[0],b=fs.readFileSync(new URL('../'+r.file,import.meta.url));assertGalleryAsset44r2(b,r);const altered=Buffer.from(b);altered[altered.length-1]^=1;assert.throws(()=>assertGalleryAsset44r2(altered,r));assert.throws(()=>assertGalleryAsset44r2(b,{...r,height:r.height+1}));assert.throws(()=>assertGalleryAsset44r2(b.subarray(0,-1),r));assert.equal(isDeferredGallery44r2('<img loading="lazy">',r.file),true);assert.equal(isDeferredGallery44r2('<img>',r.file),false);assert.equal(isDeferredGallery44r2('<script loading="lazy">',r.file),false);assert.equal(galleryStatic46.length,60);});
test('44R2 full verification requires this suite and keeps historical task44 checks',()=>{const s=read('tests/verify-orchestrator.mjs');assert.ok(s.includes('"tests/project-galleries-44r2.test.mjs"'));assert.ok(s.includes('"tests/project-proof-ui-44.test.mjs"'));assert.ok(s.includes('"tests/lead-form-runtime.test.mjs"'));assert.ok(s.includes('"tests/legacy-retirement-42r1.test.mjs"'));});
